name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    tags:
      - '*'   # Optionally, trigger on tags (useful for versioned releases)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (needed for pushing to GHCR)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}-$(basename $GITHUB_REPOSITORY):latest"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME_LOWER .
          docker tag $IMAGE_NAME_LOWER ghcr.io/${{ github.repository_owner | lower }}/$(basename $GITHUB_REPOSITORY):${{ github.sha }}

      # Step 5: Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}-$(basename $GITHUB_REPOSITORY)"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_NAME_LOWER:latest
          docker push $IMAGE_NAME_LOWER:${{ github.sha }}
